[package]
name = "minidash-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.8.4"
notify = "4.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
handlebars = "4.2.2"
gotham = "0.7.1"
gotham_derive = "0.7.0"
lazy_static = "1.4.0"